# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 361e1807f67b9e45ce051bc36c9d7c736e0ccc0a5ef56501713a03a573c5ad1c00fd15651c9374c26876c24429a712ea2115b578addb98281c861d19a09244ab

test:
  secret_key_base: f727467ffe47c0e63ba0ed44d027fa2002c7c2ac39e326b8d62b5ed330c255e09f481b78ae89d8037e8987f54a87be823d6219f54ab1adee888d912dadee131b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
